### ISSUE TITLE
Bug: Cannot read property 'active' of undefined

### ISSUE THREAD

**Issue by nik-lampe** [final-form/final-form#186]
### Are you submitting a **bug report** or a **feature request**?

**bug report**

### What is the current behavior?

I am trying to use a slider component in my form and a conditional field which is based on the field which is controlled by the slider. 

The component I'm using is this: 
https://blueprintjs.com/docs/#core/components/sliders

Showing the conditional field works just fine, but as soon as the field should disappear again, it crashes with this error message:

TypeError
Cannot read property 'active' of undefined

### Sandbox Link

Here is a sandbox with the slider:
https://codesandbox.io/s/3y197jnzq

While trying to find the cause I found that the same happens, when the value is not set by the input, but programmatically with an timeout.
I have recreated this in a sandbox (this is a really silly example, I would never actually do this, but this was the easiest way to reproduce it) 

https://codesandbox.io/s/xr4027203o

The conditionial field shows when the value is larger than 5. You can see, that manually entering a value lower than 5 works fine, but when you click the "enableTimer" button, it starts counting down from 10 and when it reaches 5 --> crash.

**Comment by Nttz** [comment]
Hi, @erikras.
One of our legacy projects, where was a similar error, decided to update the dependencies.
I reproduce example above [https://codesandbox.io/s/xr4027203o](https://codesandbox.io/s/xr4027203o):

- final-form v4.11.0 + react-final-form v4.0.2 - has error

- final-form v4.20.0 + react-final-form v6.5.0 - no error

Can you clarify if this error has been fixed or is it just an coincidence?

**Comment by sleekyom** [comment]
Hello,

I have the same error as well and I have upgraded the package to the latest version but that didn't fix the error.

This is the error i see in my console:
`final-form.es.js:181 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'active')
    at publishFieldState (final-form.es.js:181:1)
    at notifyField (final-form.es.js:741:1)
    at notifyFieldListeners (final-form.es.js:752:1)
    at notify (final-form.es.js:1089:1)
    at afterPromise (final-form.es.js:714:1)`

Any idea on how to fix this will be appreciated .

**Comment by skrivanos** [comment]
Got this happening only in Jest with 4.20.7 when a field has an `initialValue` and is conditionally rendered. Still trying to track down the exact cause.

**Comment by jarnaiz** [comment]
Hi @skrivanos I send a PR some time ago to try to fix the problem: https://github.com/final-form/final-form/pull/453

**Comment by oonsamyi** [comment]
Render Field with `display: "none"` when it does not satisfy condition resolves the problem

**Comment by jarnaiz** [comment]
I think this bug isnt already present. @gertdreyer @erikras  maybe this issue should be "resolved"

**Comment by Sergi0Limit** [comment]
This bug present in iOS 17 safari and chrome

**Comment by rbuetzer** [comment]
We encountered the same issue with Safari 17 desktop and mobile. The issue seems to be related to `Object.assign()`.

The following line

https://github.com/final-form/final-form/blob/edada3668ce21f1a75bd71386464dc79f01fbb28/src/FinalForm.js#L508 

is transpiled to the following:

```js
    var safeFields = _extends({}, fields);
```

Where `_extends()` is a [Babel polyfill](https://github.com/babel/babel/blob/e0375121bfea96d277f49543dc543f116523cfd0/packages/babel-helpers/src/helpers.ts#L165-L176) for `Object.assign()`. We noticed that in Safari sometimes, `_extends({}, fields)` returned an empty object even tough `fields` was non-empty.

 As a makeshift fix, we replaced the corresponding polyfill by its fallback. This made the issue disappear, however, we have no clue, why.

Patch for `final-form.es.js` of `final-form@4.20.10`

```patch
diff --git a/dist/final-form.es.js b/dist/final-form.es.js
index e31d7f32c686fede8d70925fbd486679adc42b38..39976022d87026f725d5b371a8fb1c843bb76892 100644
--- a/dist/final-form.es.js
+++ b/dist/final-form.es.js
@@ -1,6 +1,17 @@
-import _extends from '@babel/runtime/helpers/esm/extends';
 import _objectWithoutPropertiesLoose from '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose';
 
+const _extends = function (target) {
+  for (var i = 1; i < arguments.length; i++) {
+    var source = arguments[i];
+    for (var key in source) {
+      if (Object.prototype.hasOwnProperty.call(source, key)) {
+        target[key] = source[key];
+      }
+    }
+  }
+  return target;
+}
+
 //      
 
 var charCodeOfDot = ".".charCodeAt(0);

```

**Comment by mikew** [comment]
It's also happening in webkitgtk

**Comment by mikew** [comment]
For me, it happened after the third or fourth time loading a form on macOS, but always happened in webkitgtk on Linux. Made me think it was something going on with Webkit's JIT.

**Comment by KalachevDev** [comment]
I noticed something similar, seems it's getting worse with further reloads

**Comment by christiaanwesterbeek** [comment]
I fixed it by upgrading from final-form version "4.18.6" to "4.20.10".

I know it's an intermittent bug, so I can't be sure. But with 4.18.6, it took me about a handful of attempts to reproduce it. And with 4.20.10, I can't reproduce it after trying for 10 minutes under the same conditions.

Found the "solution" via [this comment](https://github.com/final-form/react-final-form/pull/932#issuecomment-1405811477) in a PR that linked issue #411.

**Comment by KalachevDev** [comment]
> I fixed it by upgrading from final-form version "4.18.6" to "4.20.10".
> 
> I know it's an intermittent bug, so I can't be sure. But with 4.18.6, it took me about a handful of attempts to reproduce it (in Safari 17 on macOS Sonoma). And with 4.20.10, I can't reproduce it after trying for 10 minutes under the same conditions.
> 
> Found the "solution" via [this comment](https://github.com/final-form/react-final-form/pull/932#issuecomment-1405811477) in a PR that linked issue #411.

This didn't work for me. Still reproducable at Safari17 final-form@4.20.10

**Comment by aaa-paul** [comment]
Still experiencing issues after applying the workaround/fallback suggested by [rbuetzer](https://github.com/rbuetzer).  I Also applied it to a forked version of `react-final-form`.

However I think this is because the project I'm working on is using babel which ends up adding the `Object.assign` statements for object spreads.

**Comment by sudkumar** [comment]
Hi @aaa-paul 

What @rbuetzer meant was to patch the final-form package inside the `node_modules` folder. To ensure that is stays patched for further installs, we can use the [patch-package](https://www.npmjs.com/package/patch-package). 

Here are the steps that I followed, and the issue is resolved.

1. Install the package [patch-package](https://www.npmjs.com/package/patch-package) using your package manager (npm/yarn/pnpm/bun) `npm i patch-package`
2. Make the following changes in `/node_modules/final-form/final-form.es.js`
```diff
- import _extends from '@babel/runtime/helpers/esm/extends'

// after all imports, add the  following _extends implementation
+ const _extends = function (target) {
+  for (var i = 1; i < arguments.length; i++) {
+    var source = arguments[i];
+    for (var key in source) {
+      if (Object.prototype.hasOwnProperty.call(source, key)) {
+        target[key] = source[key];
+      }
+    }
+  }
+  return target;
+}
```
3. Store the patch diff by running `npx patch-package final-form`. This should create a `patches` folder in the root directory with the respective diff of `final-form` patch. 
4. Add the following script in your `package.json`. This will ensure that the patches are automatically applies (updates to node_modules/final-form) on future `npm install`
```diff
 "scripts": {
+  "postinstall": "patch-package"
 }
```

I hope it helps. Also, I would recommend installing the exact version of `final-form` to ensure patches are correctly applied across installs and team members.
```
npm install --save-exact final-form
```

---
Thank you @rbuetzer so much for sharing your workaround. 🙏

**Comment by aaa-paul** [comment]
Thanks for sharing @sudkumar.

What I did was forked the exact versions of both final-form and react-final-form (rff I replaced the branch with the built library) and then used that branch as the dependency version in package.json.  Theoretically it should be the same thing.

However, I'll try out what you mentioned with patch-package.  Appreciate the help!

**Comment by aaa-paul** [comment]
FYI, while this isn't a solution, this issue seems to be resolved with Safari 17.1+.  All versions 17.0.X are negatively impacted.

**Comment by mikew** [comment]
Confirming this isn't happening on Safari 17.1 (well, I'm using a webview but this bug isn't being triggered anymore)

https://github.com/final-form/final-form/assets/4729/7af25efb-168c-4213-9838-9f1e1d8eb740

Before, opening the form would crash the app after the third or fourth time

Still might be an issue on webkitgtk

**Comment by mikew** [comment]
Yeah, still happening with webkitgtk-2.42.1


https://github.com/final-form/final-form/assets/4729/cddf6f29-0ee6-431c-8528-064d4146d4c6

**Comment by MartinHutyra** [comment]
I'm facing to the same issue.
safari: 17.0
final-form: 4.20.2 (this is also happening for version '4.20.10')

<img width="924" alt="Screenshot 2023-11-01 at 15 31 00" src="https://github.com/final-form/final-form/assets/49433570/5f9ce2e4-9ead-47a4-8bc6-eec29c3cebf2">

**Comment by goodwin64** [comment]
The same issue here:
final-form: `4.20.9`
react-final-form: `6.5.9` (not related to this issue specifically)
browser: Apple's [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) (Safari-like) - from Capacitor

I can confirm @rbuetzer's and @sudkumar's workarounds work. I would love to have the fix made in the library itself.

**Comment by goodwin64** [comment]
Our use case is shown here:
https://vimeo.com/893530490?share=copy

**Comment by erikras-richard-agent** [comment]
Fix published in [`v5.0.1`](https://github.com/final-form/final-form/releases/tag/v5.0.1)
