### ISSUE TITLE
Validate only changed field

### ISSUE THREAD

**Issue by sqal** [final-form/final-form#37]
### Are you submitting a **bug report** or a **feature request**?
Feature request

### What is the current behavior?
Hey :) First thanks for this great library, it is a real pleasure working with it, but let me go to the point. I have a large form containing ~20 fields. Each field has its own validation function passed in `form.registerField`, so current behaviour is as follows. If I change the value of any field, it will trigger validation of every registered field, which (in my opinion) and in most of my cases is unnecessary, especially when some field may use async validation (via ajax). I would like to kindly ask you to consider changing this behaviour. Perhaps a new option could be added to `registerField` e.g:

```js
  form.registerField(
  'someField',
  (fieldState) => {
    this.someField = fieldState
  },
  { value: true, valid: true },
  (value) => !!val,
  validateFields?: boolean | Array<string> 
  // if it's false will only trigger validation of that field, 
  // if true will trigger validation of every field, 
  // or if it's an array will validate specified fields 
)
```

### What is the expected behavior?
When field value is updated, only trigger validation function of the updated field

Thank you for looking into this.

**Comment by VladShcherbin** [comment]
@sqal when you add validation to a field, it is triggered only for this field, not for all fields.

I'm using react-final-form and it works there correctly. Maybe you can create a demo if it works for you differently.

**Comment by sqal** [comment]
@VladShcherbin I don't work with React. I use final-form with Vue, butthat doesn't matter, issue is in final-form. Here is simple reproduction: https://codesandbox.io/s/2w5l43w66j

As you can see already at the start, email validator has been called 2 times. First time called when the field is registered and second time when password field is registered. If you go and change e.g. password value, it will also call email validator again, exactly as I described earlier.

**Comment by VladShcherbin** [comment]
@sqal this is strange. I can see validation is called twice in your demo. In react the same example triggers validation only once. 😕

**Comment by sqal** [comment]
@VladShcherbin React version has the same issue, go to https://codesandbox.io/s/2k054qp40, add console log to `required` function and play with the form and check how many time this function is called.

**Comment by VladShcherbin** [comment]
@sqal yeah, you are right, there is an issue with this.

**Comment by erikras** [comment]
First of all, I'm delighted to hear someone is using this library with Vue. 😄 I also love it when someone gives a suggested solution with the problem. 👍

Sync validation is normally so fast that it doesn't matter if it gets run on every keypress for the whole form, but this makes a lot of sense for async. Also, this is in line with the goal of perf optimization.

Your suggestion is very interesting. I might flip the meanings of the boolean values, so that the default value (`false`) is the current "validate everything" behavior. The more I think about it, the more I like it.

**Comment by erikras** [comment]
Fixed published in [`final-form@2.0.0`](https://github.com/final-form/final-form/releases/tag/v2.0.0).

**Comment by sqal** [comment]
Hey @erikras. Thanks for implementing this functionality, however I found some issues with it. Updated demo: https://codesandbox.io/s/2w5l43w66j

when the validateFields is an empty array and you enter some value in the email field, password field changes its valid flag to true, and so I can submit the form. Why is this happening? And the second issue. When the validateFields contains the name of registered field, validation of that field will be called twice whenever the value changes.

**Comment by sqal** [comment]
Hi @erikras do you have an idea how to fix the issues I mentioned above? I tried latest 4.0.0 release and looks like they're still present. Also there is an error in latest release note :P. It says we should change in our code:

```
validate: value => { // return error }
```

to: 
```
validate: () => value => { // return error }
```

when in fact it should be:

```
getValidator: () => value => { // return error }
```

**Comment by erikras** [comment]
> When the `validateFields` contains the name of registered field, validation of that field will be called twice whenever the value changes.

The `validateFields` config parameter is supposed to be about _other_ fields to validate. _Obviously_ we have to validate the one that just changed, so by specifying the current field in `validateFields`, it's going to force a second validation call.

Changing your line

```jsx
validateFields: ['email'],
```
to 
```jsx
validateFields: name === 'email' ? [] : ['email'],
```

stops the double validation. I had not foreseen a `forEach` loop like this.

**Comment by erikras** [comment]
I suppose FF could run that "unless it's the current field" check, but it never occurred to me that someone might explicitly request the current field....

**Comment by janrider** [comment]
Hey @erikras. I've found same issue in my project: onChange of any field triggers validation for all fields. I've taken your example from here https://codesandbox.io/s/mmj0z72v2x where every field validates only when it was changed, and put it to my app. Now all fields validation triggered when any field changed. I'm confusing

**Comment by erikras** [comment]
@janrider Ha! That was a bug in the little `simpleMemoize()` function I created for that example. It wasn't memoizing a value of `undefined`.

Should be:
```jsx
const simpleMemoize = fn => {
  let lastArg
  let lastResult
  return arg => {
    if (arg !== lastArg) {
      lastArg = arg
      lastResult = fn(arg)
    }
    return lastResult
  }
}
```

Note that the validation is still being called, but the memoize function is preventing repeating values. If you don't want other fields' validation to be run, you can specify `validateFields={[]}` in your `Field` components. [See docs](https://github.com/final-form/final-form#validatefields-string).

**Comment by janrider** [comment]
I've missed this `validateFields={[]}` option. This helped, thanks a lot!
